name: cd

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dotnet-install
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: dotnet-restore
      run: dotnet restore
    - name: dotnet-build
      run: dotnet build --no-restore
    - name: docker-login
      shell: pwsh
      run: |
        echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username netdefender --password-stdin
    - name: publish
      run: dotnet publish BlazorApp/BlazorApp.csproj -p:PublishProfile=DefaultContainer -c Release -p:ContainerRegistry=docker.io
